---
kind: pipeline
type: docker
name: coding-standard-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: coding-standard-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-php7.1-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: daily-master-qa

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.2-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: daily-master-qa

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: phpunit-php7.3-mysql5.5

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: daily-master-qa

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit

services:
- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: webUIFirstrunwiz-master-chrome-mariadb10.2-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: daily-master-qa

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/firstrunwizard /var/www/owncloud/server/apps/

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - chown -R www-data /var/www/owncloud/server

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-webui
  environment:
    APPS_TO_ENABLE: firstrunwizard
    BEHAT_SUITE: webUIFirstrunwizard
    BROWSER: chrome
    PLATFORM: Linux
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
    TEST_SERVER_URL: http://server

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: selenium
  pull: always
  image: selenium/standalone-chrome-debug:3.141.59-oxygen
  environment:
    JAVA_OPTS: -Dselenium.LOGGER.level=WARNING

- name: server
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: webUIFirstrunwiz-master-firefox-mariadb10.2-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: daily-master-qa

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/firstrunwizard /var/www/owncloud/server/apps/

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - chown -R www-data /var/www/owncloud/server

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-webui
  environment:
    APPS_TO_ENABLE: firstrunwizard
    BEHAT_SUITE: webUIFirstrunwizard
    BROWSER: firefox
    PLATFORM: Linux
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
    TEST_SERVER_URL: http://server

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: selenium
  pull: always
  image: selenium/standalone-firefox-debug:3.8.1
  environment:
    JAVA_OPTS: -Dselenium.LOGGER.level=WARNING
    SE_OPTS: -enablePassThrough false

- name: server
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: webUIFirstrunwiz-latest-chrome-mariadb10.2-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: latest

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/firstrunwizard /var/www/owncloud/server/apps/

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - chown -R www-data /var/www/owncloud/server

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-webui
  environment:
    APPS_TO_ENABLE: firstrunwizard
    BEHAT_SUITE: webUIFirstrunwizard
    BROWSER: chrome
    PLATFORM: Linux
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
    TEST_SERVER_URL: http://server

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: selenium
  pull: always
  image: selenium/standalone-chrome-debug:3.141.59-oxygen
  environment:
    JAVA_OPTS: -Dselenium.LOGGER.level=WARNING

- name: server
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: webUIFirstrunwiz-latest-firefox-mariadb10.2-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: testrunner/apps/firstrunwizard

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mariadb
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    exclude: apps/firstrunwizard
    version: latest

- name: install-testrunner
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir /tmp/testrunner
  - git clone -b master --depth=1 https://github.com/owncloud/core.git /tmp/testrunner
  - rsync -aIX /tmp/testrunner /var/www/owncloud
  - cp -r /var/www/owncloud/testrunner/apps/firstrunwizard /var/www/owncloud/server/apps/

- name: setup-server-firstrunwizard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e firstrunwizard
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: owncloud-log-server
  pull: always
  image: owncloud/ubuntu:18.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - chown -R www-data /var/www/owncloud/server

- name: acceptance-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - touch /var/www/owncloud/saved-settings.sh
  - . /var/www/owncloud/saved-settings.sh
  - make test-acceptance-webui
  environment:
    APPS_TO_ENABLE: firstrunwizard
    BEHAT_SUITE: webUIFirstrunwizard
    BROWSER: firefox
    PLATFORM: Linux
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
    TEST_SERVER_URL: http://server

services:
- name: mariadb
  pull: always
  image: mariadb:10.2
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

- name: selenium
  pull: always
  image: selenium/standalone-firefox-debug:3.8.1
  environment:
    JAVA_OPTS: -Dselenium.LOGGER.level=WARNING
    SE_OPTS: -enablePassThrough false

- name: server
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1
- coding-standard-php7.2
- coding-standard-php7.3

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

depends_on:
- phpunit-php7.1-mysql5.5
- phpunit-php7.2-mysql5.5
- phpunit-php7.3-mysql5.5
- webUIFirstrunwiz-master-chrome-mariadb10.2-php7.1
- webUIFirstrunwiz-master-firefox-mariadb10.2-php7.1
- webUIFirstrunwiz-latest-chrome-mariadb10.2-php7.1
- webUIFirstrunwiz-latest-firefox-mariadb10.2-php7.1

...
